version: "3.8"
services:
  app:
    container_name: app
    build:
      context: ./games
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    ports:
      - "80:80"
  postgres:
    container_name: postgres
    build:
      context: ./games/dev
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: webdbuser
      POSTGRES_DB: webdb
    ports:
      - "5432:5432"